In [1]:
import numpy as np

In [2]:
def sigmoid(S):
    """
    S: an numpy array
    return sigmoid function for each element in S
    """
    return 1/(1+np.exp(-S))

In [112]:
def prob(w, X):
    """
    X: a numpy array of shape (N, d), N datapoint, each with size d
    w: a numpy array of shape (d)
    """
    return sigmoid(X.dot(w))

In [111]:
def loss(w, X, y, lam):
    """
    X, w as in prob
    y: a 1d numpy array of shape (N). Each elem = 0 or 1
    """
    z = prob(w, X)
    return -np.mean(y*np.log(z) + (1-y)*np.log(1-z)) + 0.5*lam/X.shape[0]*np.sum(w*w)

In [52]:
def logistic_regression(w_init, X, y, lam = 0.001, lr = 0.1, nepoches = 2000):
    #lam - reg parameter, lr-learning rate, nepoches - number of epoches
    N, d = X.shape[0], X.shape[1]
    w = w_old = w_init
    loss_hist = [loss(w_init, X, y, lam)]
    ep = 0
    while ep < nepoches:
        ep += 1
        z = sigmoid(X.dot(w))
        w = w - lr*(X.T.dot((y-z)) + lam*w)
        loss_hist.append(loss(w, X, y, lam))
        if np.linalg.norm(w - w_old)/d < 1e-6:
            break
        w_old = w
        return w, loss_hist

In [124]:
def predict(w, X, threshold = 0.5):
    """
    predict output of each row of X
    X: anumpy array of shape (N,d)
    threshold: a threshold between 0 and 1 
    return a 1d numpy array, each eleemtn is 0 or 1
    """
    res = np.zeros(X.shape[0]).T
    #np.where(condition) return the filtered index
    res[np.where(prob(w, X) > threshold)[0]] = 1
    return res

In [105]:
X = np.array([[0.50, 0.75, 1.00, 1.25, 1.50, 1.75, 1.75, 2.00, 2.25, 2.50,
             2.75, 3.00, 3.25, 3.50, 4.00, 4.25, 4.50, 4.75, 5.00, 5.50]]).T
y = np.array([[0,0,0,0,0,0,1,0,1,0,1,0,1,0,1,1,1,1,1,1]]).T

In [106]:
y.shape

(20, 1)

In [107]:
X.shape

(20, 1)

In [96]:
N = X.shape[0]
Xbar = np.concatenate((X, np.ones((N, 1))), axis = 1)
w_init = np.random.randn(Xbar.shape[1]).reshape(-1,1)
lam = 0.0001

In [97]:
w_init.shape

(2, 1)

In [98]:
w, loss_hist = logistic_regression(w_init, Xbar, y, lam, lr = 0.05, nepoches = 25000000)

In [99]:
w

array([[-1.89027707],
       [ 2.91610865]])

In [100]:
print(loss(w, Xbar, y, lam))

2.5780190732054833


In [101]:
x = np.random.permutation(6).reshape(-1,1)
x.shape

(6, 1)

In [127]:
prob(w, Xbar)

array([[8.77715275e-01],
       [8.17335847e-01],
       [7.36106962e-01],
       [6.34892140e-01],
       [5.20162321e-01],
       [4.03265719e-01],
       [4.03265719e-01],
       [2.96411392e-01],
       [2.08001408e-01],
       [1.40688407e-01],
       [9.26118419e-02],
       [5.98204906e-02],
       [3.81515015e-02],
       [2.41302919e-02],
       [9.51806890e-03],
       [5.95489560e-03],
       [3.72061711e-03],
       [2.32268176e-03],
       [1.44922407e-03],
       [5.63705213e-04]])

In [126]:
predict(w, Xbar)

array([1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])